services:
  - type: web
    name: exam-prediction-ml-service
    env: python
    buildCommand: pip install --upgrade pip && pip install --no-cache-dir --only-binary :all: -r requirements.txt || pip install --only-binary :all: -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
